Upgrade gems due to a security bug fix in Nokigiri
…and general feature enhancements.

Note: commonmarker ~> 0.18.0 currently breaks the app due to
TypeError: option ':SAFE' does not exist for CommonMarker::Config::Render

…hence the version pinning.