added "json" to Gemfile
I got the following error until I added "json" to the Gemfile, when trying to install lobsters

rake db:schema:load
rake aborted!
LoadError: cannot load such file -- json
/home/ec2-user/.gem/ruby/2.3/gems/activesupport-5.1.1/lib/active_support/core_ext/object/json.rb:2:in `require'