Update typedstore gem
Old version was causing the following issue
```
NoMethodError:
       undefined method `accessor' for an instance of ActiveRecord::Type::Text
```