fix commonmarker install following #1838
I got an error (pasted below, for others) building commonmarker's native
extension (comrak) before prebuilt was available; adding libclang-dev fixed it.
Same issue for previous version: https://github.com/gjtorikian/commonmarker/issues/268

```
thread 'main' (703001) panicked at
/home/deploy/lobsters/shared/bundle/ruby/4.0.0/gems/commonmarker-2.6.0/ext/commonmarker/.rb-sys/stable/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rb-sys-0.9.117/build/main.rs:50:6:
  generate bindings: ClangDiagnostic("/home/deploy/.asdf/installs/ruby/4.0.0/include/ruby-4.0.0/ruby/ruby.h:23:10: fatal error: 'stdarg.h' file not found\n")
  stack backtrace:
     0: __rustc::rust_begin_unwind
     1: core::panicking::panic_fmt
     2: core::result::unwrap_failed
     3: core::result::Result<T,E>::expect
     4: build_script_main::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:581: target/release/libcommonmarker.so] Error 101

make failed, exit code 2

Gem files will remain installed in /home/deploy/lobsters/shared/bundle/ruby/4.0.0/gems/commonmarker-2.6.0 for inspection.
Results logged to /home/deploy/lobsters/shared/bundle/ruby/4.0.0/extensions/x86_64-linux/4.0.0/commonmarker-2.6.0/gem_make.out
```