Fix ActiveRecord::Migration inheriting without rails release
Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateInvitations < ActiveRecord::Migration[4.2]

Done with:
`sed -i -e 's@ < ActiveRecord::Migration$@ < ActiveRecord::Migration[4.2]@g' *.rb`